# Generated by Django 4.2.5 on 2025-02-06 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0002_message_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
    ]
